# Generated by Django 6.0.4 on 2026-04-28 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pais', models.CharField(max_length=30)),
                ('descripcio', models.CharField(max_length=50)),
                ('pagina_document', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValorEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_origen', models.CharField(max_length=10)),
                ('valor_upc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('matricula', models.BooleanField()),
                ('id_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escales.escala')),
            ],
        ),
    ]
