# Generated by Django 6.0.4 on 2026-05-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='descripcio',
            new_name='id_escala',
        ),
        migrations.RenameField(
            model_name='valorescala',
            old_name='id_escala',
            new_name='escala',
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('nom_pais', 'id_escala')},
        ),
        migrations.AlterUniqueTogether(
            name='valorescala',
            unique_together={('escala', 'valor_origen')},
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('num_pagina', models.IntegerField(primary_key=True, serialize=False)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escales.escala')),
            ],
        ),
    ]
