# Generated by Django 6.0.4 on 2026-05-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0002_rename_descripcio_escala_id_escala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='pagina_document',
        ),
    ]
