# Generated by Django 6.0.4 on 2026-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escales", "0003_remove_escala_pagina_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="escala",
            name="slug",
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
