# Generated by Django 6.0.4 on 2026-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0005_alter_escala_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
