# Generated by Django 6.0.4 on 2026-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0006_alter_escala_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nom_pais', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='escala',
            name='nom_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escales.pais'),
        ),
        migrations.CreateModel(
            name='Universitat',
            fields=[
                ('codi_universitat', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_universitat', models.CharField(max_length=50)),
                ('facultat', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escales.escala')),
            ],
        ),
    ]
