# Generated by Django 6.0.4 on 2026-05-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0007_pais_alter_escala_nom_pais_universitat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'verbose_name': 'Escala', 'verbose_name_plural': 'Escales'},
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name': 'Pàgina', 'verbose_name_plural': 'Pàgines'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Països'},
        ),
        migrations.AlterModelOptions(
            name='valorescala',
            options={'verbose_name': 'Valor escala', 'verbose_name_plural': 'Valors escales'},
        ),
    ]
