# Generated by Django 6.0.4 on 2026-05-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0008_alter_escala_options_alter_pagina_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Països'},
        ),
    ]
