# Generated by Django 6.0.4 on 2026-05-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0009_alter_pais_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitat',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escales.pais'),
        ),
        migrations.AddField(
            model_name='universitat',
            name='programa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
