# Generated by Django 6.0.4 on 2026-05-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0010_universitat_pais_universitat_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitat',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escales.pais'),
        ),
    ]
