# Generated by Django 6.0.4 on 2026-05-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0011_alter_universitat_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitat',
            name='programa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
