# Generated by Django 6.0.4 on 2026-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0012_alter_universitat_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitat',
            name='facultat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='universitat',
            name='nom_universitat',
            field=models.CharField(max_length=100),
        ),
    ]
