# Generated by Django 6.0.4 on 2026-05-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0013_alter_universitat_facultat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitat',
            name='escala',
        ),
        migrations.AddField(
            model_name='universitat',
            name='escala',
            field=models.ManyToManyField(blank=True, to='escales.escala'),
        ),
    ]
