# Generated by Django 6.0.4 on 2026-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0014_remove_universitat_escala_universitat_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitat',
            name='programa',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
