# Generated by Django 6.0.4 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0015_alter_universitat_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorescala',
            name='valor_upc',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
