# Generated by Django 6.0.4 on 2026-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escales', '0016_alter_valorescala_valor_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitat',
            name='domini',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
