import requests
import os

DOMINI_MAP = {
    "hust.edu.vn": "hust.edu.vn",
    "udelar.edu.uy": "udelar.edu.uy",
    "illinois.edu": "illinois.edu",
    "gatech.edu": "gatech.edu",
    "coventry.ac.uk": "coventry.ac.uk",
    "ntu.edu.tw": "ntu.edu.tw",
    "stuba.sk": "stuba.sk",
    "um.si": "um.si",
    "oulu.fi": "oulu.fi",
    "aalto.fi": "aalto.fi",
    "uu.se": "uu.se",
    "umu.se": "umu.se",
    "kth.se": "kth.se",
    "liu.se": "liu.se",
    "bth.se": "bth.se",
    "chalmers.se": "chalmers.se",
    "upb.ro": "upb.ro",
    "pwr.edu.pl": "pwr.edu.pl",
    "pw.edu.pl": "pw.edu.pl",
    "put.poznan.pl": "put.poznan.pl",
    "p.lodz.pl": "p.lodz.pl",
    "agh.edu.pl": "agh.edu.pl",
    "pg.edu.pl": "pg.edu.pl",
    "ug.edu.pl": "ug.edu.pl",
    "pucp.edu.pe": "pucp.edu.pe",
    "iscap.ipp.pt": "iscap.ipp.pt",
    "fe.up.pt": "fe.up.pt",
    "fc.up.pt": "fc.up.pt",
    "tecnico.ulisboa.pt": "tecnico.ulisboa.pt",
    "ciencias.ulisboa.pt": "ciencias.ulisboa.pt",
    "uc.pt": "uc.pt",
    "uminho.pt": "uminho.pt",
    "maastrichtuniversity.nl": "maastrichtuniversity.nl",
    "saxion.nl": "saxion.nl",
    "utwente.nl": "utwente.nl",
    "tue.nl": "tue.nl",
    "fontys.nl": "fontys.nl",
    "tudelft.nl": "tudelft.nl",
    "uva.nl": "uva.nl",
    "ntnu.no": "ntnu.no",
    "oslomet.no": "oslomet.no",
    "uib.no": "uib.no",
    "tec.mx": "tec.mx",
    "rtu.lv": "rtu.lv",
    "uni.lu": "uni.lu",
    "vgtu.lt": "vgtu.lt",
    "inu.ac.kr": "inu.ac.kr",
    "titech.ac.jp": "titech.ac.jp",
    "ucd.ie": "ucd.ie",
    "polito.it": "polito.it",
    "unisa.it": "unisa.it",
    "uniroma1.it": "uniroma1.it",
    "unipg.it": "unipg.it",
    "unipd.it": "unipd.it",
    "unina.it": "unina.it",
    "polimi.it": "polimi.it",
    "unimi.it": "unimi.it",
    "unica.it": "unica.it",
    "unibs.it": "unibs.it",
    "unibo.it": "unibo.it",
    "univaq.it": "univaq.it",
    "uniba.it": "uniba.it",
    "bme.hu": "bme.hu",
    "unizg.hr": "unizg.hr",
    "tuc.gr": "tuc.gr",
    "ntua.gr": "ntua.gr",
    "uniwa.gr": "uniwa.gr",
    "insa-toulouse.fr": "insa-toulouse.fr",
    "u-psud.fr": "u-psud.fr",
    "insa-rennes.fr": "insa-rennes.fr",
    "sorbonne-universite.fr": "sorbonne-universite.fr",
    "u-paris.fr": "u-paris.fr",
    "polytechnique.edu": "polytechnique.edu",
    "univ-paris-est.fr": "univ-paris-est.fr",
    "ec-nantes.fr": "ec-nantes.fr",
    "univ-nantes.fr": "univ-nantes.fr",
    "univ-lorraine.fr": "univ-lorraine.fr",
    "umontpellier.fr": "umontpellier.fr",
    "centrale-marseille.fr": "centrale-marseille.fr",
    "insa-lyon.fr": "insa-lyon.fr",
    "univ-lyon1.fr": "univ-lyon1.fr",
    "ec-lyon.fr": "ec-lyon.fr",
    "centralelille.fr": "centralelille.fr",
    "grenoble-inp.fr": "grenoble-inp.fr",
    "universite-paris-saclay.fr": "universite-paris-saclay.fr",
    "uca.fr": "uca.fr",
    "imt-mines-albi.fr": "imt-mines-albi.fr",
    "taltech.ee": "taltech.ee",
    "unizar.es": "unizar.es",
    "upv.es": "upv.es",
    "uv.es": "uv.es",
    "ull.es": "ull.es",
    "urv.cat": "urv.cat",
    "us.es": "us.es",
    "usc.es": "usc.es",
    "unavarra.es": "unavarra.es",
    "uib.es": "uib.es",
    "uniovi.es": "uniovi.es",
    "um.es": "um.es",
    "uma.es": "uma.es",
    "upm.es": "upm.es",
    "uam.es": "uam.es",
    "ucm.es": "ucm.es",
    "ulpgc.es": "ulpgc.es",
    "ugr.es": "ugr.es",
    "ehu.eus": "ehu.eus",
    "uco.es": "uco.es",
    "uji.es": "uji.es",
    "uca.es": "uca.es",
    "ua.es": "ua.es",
    "uva.es": "uva.es",
    "uc3m.es": "uc3m.es",
    "sdu.dk": "sdu.dk",
    "dtu.dk": "dtu.dk",
    "ku.dk": "ku.dk",
    "uni-saarland.de": "uni-saarland.de",
    "tum.de": "tum.de",
    "uni-marburg.de": "uni-marburg.de",
    "uni-mannheim.de": "uni-mannheim.de",
    "uni-leipzig.de": "uni-leipzig.de",
    "kit.edu": "kit.edu",
    "uni-hannover.de": "uni-hannover.de",
    "uni-freiburg.de": "uni-freiburg.de",
    "uni-frankfurt.de": "uni-frankfurt.de",
    "fau.de": "fau.de",
    "tu-darmstadt.de": "tu-darmstadt.de",
    "rub.de": "rub.de",
    "tu-berlin.de": "tu-berlin.de",
    "rwth-aachen.de": "rwth-aachen.de",
    "uni-wuerzburg.de": "uni-wuerzburg.de",
    "uni-stuttgart.de": "uni-stuttgart.de",
    "cvut.cz": "cvut.cz",
    "vut.cz": "vut.cz",
    "ucy.ac.cy": "ucy.ac.cy",
    "tongji.edu.cn": "tongji.edu.cn",
    "hku.hk": "hku.hk",
    "buaa.edu.cn": "buaa.edu.cn",
    "bit.edu.cn": "bit.edu.cn",
    "pucv.cl": "pucv.cl",
    "usach.cl": "usach.cl",
    "uchile.cl": "uchile.cl",
    "ethz.ch": "ethz.ch",
    "epfl.ch": "epfl.ch",
    "hes-so.ch": "hes-so.ch",
    "polymtl.ca": "polymtl.ca",
    "mcgill.ca": "mcgill.ca",
    "usp.br": "usp.br",
    "ucb.edu.bo": "ucb.edu.bo",
    "tu-sofia.bg": "tu-sofia.bg",
    "uni-sofia.bg": "uni-sofia.bg",
    "uclouvain.be": "uclouvain.be",
    "ugent.be": "ugent.be",
    "ulb.ac.be": "ulb.ac.be",
    "uantwerpen.be": "uantwerpen.be",
    "kuleuven.be": "kuleuven.be",
    "unimelb.edu.au": "unimelb.edu.au",
    "uba.ar": "uba.ar",
    "javeriana.edu.co": "javeriana.edu.co",
    "tuwien.ac.at": "tuwien.ac.at",
    "fhv.at": "fhv.at",
    "plus.ac.at": "plus.ac.at",
    "tugraz.at": "tugraz.at",
}

output_dir = "static/favicons"
os.makedirs(output_dir, exist_ok=True)

ok = 0
fail = 0

for domini in set(DOMINI_MAP.values()):
    url = f"https://www.google.com/s2/favicons?domain={domini}&sz=32"
    filename = os.path.join(output_dir, f"{domini}.png")

    if os.path.exists(filename):
        print(f"→ Ja existeix: {domini}")
        ok += 1
        continue

    try:
        r = requests.get(url, timeout=10)
        if r.status_code == 200:
            with open(filename, "wb") as f:
                f.write(r.content)
            print(f"✓ {domini}")
            ok += 1
        else:
            print(f"✗ Error {r.status_code}: {domini}")
            fail += 1
    except Exception as e:
        print(f"✗ {domini}: {e}")
        fail += 1

print(f"\nResultat: {ok} descarregats, {fail} fallits.")
