# Generated by Django 6.0.4 on 2026-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escales', '0007_pais_alter_escala_nom_pais_universitat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursAcademic',
            fields=[
                ('curs', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Durada',
            fields=[
                ('tipus', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('ANUAL', 'Anual')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiant',
            fields=[
                ('codi_exp_mob', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('primer_cognom', models.CharField(max_length=30)),
                ('segon_cognom', models.CharField(blank=True, max_length=30)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('codi_exp', models.CharField(max_length=20, unique=True)),
                ('centre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeMobilitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilitat.cursacademic')),
                ('durada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilitat.durada')),
            ],
            options={
                'unique_together': {('curs', 'durada')},
            },
        ),
        migrations.CreateModel(
            name='Mobilitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilitat.estudiant')),
                ('universitat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escales.universitat')),
                ('periode_mobilitat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilitat.periodemobilitat')),
            ],
            options={
                'unique_together': {('periode_mobilitat', 'universitat', 'estudiant')},
            },
        ),
    ]
