# Generated by Django 6.0.4 on 2026-05-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilitat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursacademic',
            options={'verbose_name': 'Curs acadèmic', 'verbose_name_plural': 'Cursos acadèmics'},
        ),
        migrations.AlterModelOptions(
            name='durada',
            options={'verbose_name': 'Durada', 'verbose_name_plural': 'Durades'},
        ),
        migrations.AlterModelOptions(
            name='periodemobilitat',
            options={'verbose_name': 'Període mobilitat', 'verbose_name_plural': 'Períodes mobilitat'},
        ),
    ]
