from django import template
from django.utils.safestring import mark_safe

register = template.Library()

COUNTRY_FLAGS = {
    "AFGANISTAN": "af",
    "ALBANIA": "al",
    "ALEMANIA": "de",
    "ANDORRA": "ad",
    "ANGOLA": "ao",
    "ARABIA SAUDITA": "sa",
    "ARGELIA": "dz",
    "ARGENTINA": "ar",
    "ARMENIA": "am",
    "AUSTRALIA": "au",
    "AUSTRIA": "at",
    "AZERBAIYAN": "az",
    "BANGLADESH": "bd",
    "BELGICA": "be",
    "BELICE": "bz",
    "BENIN": "bj",
    "BIELORRUSIA": "by",
    "BOLIVIA": "bo",
    "BOSNIA HERZEGOVINA": "ba",
    "BRASIL": "br",
    "BULGARIA": "bg",
    "CABO VERDE": "cv",
    "CAMBOYA": "kh",
    "CAMERUN": "cm",
    "CANADA": "ca",
    "CHILE": "cl",
    "CHINA": "cn",
    "CHINA TAIPEI": "tw",
    "CHIPRE": "cy",
    "COLOMBIA": "co",
    "COSTA RICA": "cr",
    "CROACIA": "hr",
    "CUBA": "cu",
    "DINAMARCA": "dk",
    "ECUADOR": "ec",
    "EGIPTO": "eg",
    "EL SALVADOR": "sv",
    "EMIRATOS ARABES UNIDOS": "ae",
    "ERITREA": "er",
    "ESLOVAQUIA": "sk",
    "ESLOVENIA": "si",
    "ESPAÑA": "es",
    "ESTADOS UNIDOS DE AMERICA": "us",
    "ESTONIA": "ee",
    "ETIOPIA": "et",
    "FIJI": "fj",
    "FILIPINAS": "ph",
    "FINLANDIA": "fi",
    "FRANCIA": "fr",
    "GABON": "ga",
    "GEORGIA": "ge",
    "GHANA": "gh",
    "GRECIA": "gr",
    "GUATEMALA": "gt",
    "GUINEA": "gn",
    "GUINEA ECUATORIAL": "gq",
    "GUINEA-BISSAU": "gw",
    "HONDURAS": "hn",
    "HONG KONG": "hk",
    "HUNGRIA": "hu",
    "INDIA": "in",
    "INDONESIA": "id",
    "IRAN": "ir",
    "IRAQ": "iq",
    "IRLANDA": "ie",
    "ISLANDIA": "is",
    "ISRAEL": "il",
    "ITALIA": "it",
    "JAMAICA": "jm",
    "JAPON": "jp",
    "JORDANIA": "jo",
    "KAZAJSTAN": "kz",
    "KENIA": "ke",
    "KIRGUISTAN": "kg",
    "LETONIA": "lv",
    "LIBANO": "lb",
    "LIBIA": "ly",
    "LITUANIA": "lt",
    "LUXEMBURGO": "lu",
    "MACAO": "mo",
    "MACEDONIA": "mk",
    "MADAGASCAR": "mg",
    "MALASIA": "my",
    "MALTA": "mt",
    "MARRUECOS": "ma",
    "MAURITANIA": "mr",
    "MEXICO": "mx",
    "MONGOLIA": "mn",
    "MONTENEGRO": "me",
    "MOZAMBIQUE": "mz",
    "NAMIBIA": "na",
    "NEPAL": "np",
    "NICARAGUA": "ni",
    "NIGERIA": "ng",
    "NORUEGA": "no",
    "NUEVA ZELANDA": "nz",
    "PAISES BAJOS": "nl",
    "PAKISTAN": "pk",
    "PALESTINA": "ps",
    "PANAMA": "pa",
    "PARAGUAY": "py",
    "PERU": "pe",
    "POLONIA": "pl",
    "PORTUGAL": "pt",
    "PUERTO RICO": "pr",
    "REINO UNIDO": "gb",
    "REPUBLICA CHECA": "cz",
    "REPUBLICA DE COREA": "kr",
    "REPUBLICA DE MOLDAVIA": "md",
    "REPUBLICA DE SERBIA": "rs",
    "REPUBLICA DEL YEMEN": "ye",
    "REPUBLICA DEMOCRATICA DEL CONGO": "cd",
    "REPUBLICA DOMINICANA": "do",
    "REPUBLICA SUDAFRICANA": "za",
    "RUANDA": "rw",
    "RUMANIA": "ro",
    "RUSIA": "ru",
    "SANTO TOME Y PRINCIPE": "st",
    "SENEGAL": "sn",
    "SINGAPUR": "sg",
    "SIRIA": "sy",
    "SRI LANKA": "lk",
    "SUDÁN": "sd",
    "SUECIA": "se",
    "SUIZA": "ch",
    "TAILANDIA": "th",
    "TANZANIA": "tz",
    "TAYIKISTAN": "tj",
    "TOGO": "tg",
    "TUNEZ": "tn",
    "TURKMENISTAN": "tm",
    "TURQUIA": "tr",
    "UCRANIA": "ua",
    "UGANDA": "ug",
    "URUGUAY": "uy",
    "UZBEKISTAN": "uz",
    "VATICANO": "va",
    "VENEZUELA": "ve",
    "VIETNAM": "vn",
    "ZAMBIA": "zm",
    "ZIMBABWE": "zw",
}


@register.simple_tag
def flag_icon(pais):
    nom = str(pais).upper() if pais else ""
    code = COUNTRY_FLAGS.get(nom)
    if code:
        return mark_safe(f'<span class="fi fi-{code}"></span>')
    return mark_safe("🌍")
